# Generated by Django 2.1.7 on 2019-02-16 23:06

import FPS_DDBB.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FPS',
            fields=[
                ('ID_FPS', models.AutoField(primary_key=True, serialize=False)),
                ('signup_date', models.DateTimeField(verbose_name='Date of registration')),
                ('location', models.CharField(max_length=200)),
                ('group_access', models.IntegerField()),
            ],
            options={
                'db_table': 'fps',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('ID_log', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Scan date')),
                ('access_granted', models.IntegerField()),
                ('ID_FPS', models.ForeignKey(db_column='ID_FPS', on_delete=django.db.models.deletion.CASCADE, to='FPS_DDBB.FPS')),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID_user', models.IntegerField(primary_key=True, serialize=False, validators=[FPS_DDBB.models.validate_maxusers])),
                ('user_name', models.CharField(max_length=200)),
                ('group_user', models.IntegerField()),
                ('fingerprint_data', models.BinaryField()),
                ('fingerprint_hash', models.IntegerField()),
                ('fingerprint_scan_date', models.DateTimeField(verbose_name='Date of last scan')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='log',
            name='ID_user',
            field=models.ForeignKey(db_column='ID_user', on_delete=django.db.models.deletion.CASCADE, to='FPS_DDBB.User'),
        ),
    ]
